server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/jpa
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      platform: postgres
      schema-locations:
        - classpath:sql/*.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
#    hibernate:
#      ddl-auto: update
    defer-datasource-initialization: true # make sure schema sql run before data.sql

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE