server:
  port: 8888
spring:
  cloud:
    gateway:
      routes: # you can also use java code configure it.
        - id: spring-cloud-eureka-client1
          uri: http://localhost:8084/
          predicates:
            - Path=/greeting/**
        - id: consumer
          uri: http://localhost:8083/
          predicates:
            - Path=/store/**