server:
  port: 9501
spring:
  profiles:
    active: dev
  application:
    name: cloud-auth2-api
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost