server:
  port: 8083
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
resilience4j:
  circuitbreaker:
    instances:
      spring-cloud-eureka-client1:
        registerHealthIndicator: true
        slidingWindowSize: 7
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 6
logging:
  level:
    root: info
  pattern:
    console: "%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}} %m%n"